[package]
name = "IoT-dashboard-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.8.0"
tokio = { version = "1.36", features = ["sync"] }
rumqttc = "0.17.0"

[build-dependencies]
slint-build = "1.8.0"