import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    in property <string> fetched_data: "Waiting for temperature data..";
    VerticalBox {
        Text {
            text: fetched_data; // Bind the text to the property
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: 18px;
        }
    }
}
